services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smusl-app
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - app-data:/app/data
      - public-uploads:/app/public/uploads
    environment:
      - DATABASE_URL=file:/app/data/prod.db

volumes:
  app-data:
    name: smusl-app-data
  public-uploads:
    name: smusl-public-uploads
